company_operations/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from .views import list_of_hfcs, certain_hfc, inventory_tracking_purchase_delivery, inventory_tracking_wht_delivery

urlpatterns = [
    url(r'^it_purchases/$', inventory_tracking_purchase_delivery, name='inventory_tracking_purchase_delivery'),
    url(r'^it_whts/$', inventory_tracking_wht_delivery, name='inventory_tracking_wht_delivery'),
    url(r'^hfc/(?P<id>[\d]+)/$', certain_hfc, name='certain_hfc'),
    url(r'^hfcs/$', list_of_hfcs, name='list_of_hfcs'),
]

erp/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include

# for images
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simulation/', include(('simulation.urls', 'simulation'), namespace='simulation')),
    url(r'^accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^general_accounting/', include(('general_accounting.urls', 'general_accounting'), namespace='general_accounting')),
    url(r'^company_operations/', include(('company_operations.urls', 'company_operations'), namespace='company_operations')),
]


# for images
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

general_accounting/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from .views import get_accounting_balance, get_trial_balance, accounting_main_page, list_of_abs, list_of_tbs, certain_tb, certain_ab

urlpatterns = [
    url(r'^accounting_main_page/$', accounting_main_page, name='accounting_main_page'),
    url(r'^accounting_balance/$', get_accounting_balance, name='accounting_balance'),
    url(r'^trial_balance/$', get_trial_balance, name='trial_balance'),
    url(r'^list_of_abs/$', list_of_abs, name='list_of_abs'),
    url(r'^list_of_tbs/$', list_of_tbs, name='list_of_tbs'),
    url(r'^trial_balance/(?P<id>[\d]+)/$', certain_tb, name='certain_tb'),
    url(r'^accounting_balance/(?P<id>[\d]+)/$', certain_ab, name='certain_ab'),
    # url(r'^perform_operations/', perform_operations, name='perform_operations'),
]

simulation/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from .views import simulation_page, simulation_create, simulate, current_simulation_info, simulation_auto_create, simulation_model_inner_data

urlpatterns = [
    url(r'^simulation_page/', simulation_page, name='simulation_page'),
    url(r'^simulation_create/', simulation_create, name='simulation_create'),
    url(r'^simulation_auto_create/', simulation_auto_create, name='simulation_auto_create'),
    url(r'^simulate/(?P<action>[\w]+)/', simulate, name='simulate'), # start / stop
    url(r'^simulation_refresh/', current_simulation_info, name='current_simulation_info'),
    url(r'^simulation_data/', simulation_model_inner_data, name='simulation_data'),
]

simulation/forms.py
from django import forms
from .models import Simulation

class SimulationForm(forms.ModelForm):

    class Meta:
        model = Simulation
        fields = [
            # # after that - CompanyConsts will be populated

            # # to CommunalServisePayment
            # "minimal_zp", # float 4173
            # "pharmacys_sizes", # float - every is identical to easy calc 40
            # "department_size", # float - every is identical to easy calc 300
            # "tax_property_size_limit", # float 60.0
            # "pharmacys_spendingds", # Array(int, int) - to easy performed random (300-500)
            # "department_spendingds", # Array(int, int) - to easy performed random (3000-5000)

            # # to Veh_repair_Payment
            # "veh_repair_price_month", # Array(int, int) - to easy performed random [3000,6000]
            # "vehicles_num", # int ph_num / 5   15% - задержка при доставке
            # "vehicle_price", # float
            # "fuel_price", # float
            # "fuel_type", # str
            # "vehicle_consumption", # float

            # # Purchase
            # "delivery_added_time_koef", # float == 1.15 (must be >=  1)
            # # сколько на 1 аптеку машин для доставки  44 апт - 2, 4, 11, 22, 44 выбрать
            # # ****to be calculated in pre_save model ******** "num_of_phs_on_1_vehicle" ""int"" # = int(WaheHouse.objects.all().count() / vehicles_num)  # уеличение времени на реализацию доставки  столько раз сколько аптек 
            # # default in model "warehouse_num"  -  int =  44

            # # for Department
            # # "dpt_address", # str "Nezalezhnosti Blvd, 12, Brovary, Kyivs'ka oblast, Ukraine, 07400"
            # # "dpt_organisation", # str "Сеть Аптек 'Копейка'"
            # # taxes leave auto not changable



            # все изменяемо кроме warehouse_num и тех что считаются в ресивере




            # to CommunalServisePayment
            "percent_pre_buy",
            "minimal_zp",#models.IntegerField()
            "pharmacys_sizes",#models.FloatField()
            "department_size",#models.FloatField()
            "tax_property_size_limit",#models.FloatField()
            "pharmacys_spendingds",#models.ArrayField(models.IntegerField(), size=2)
            "department_spendingds",#models.ArrayField(models.IntegerField(), size=2)

            # to Veh_repair_Payment
            "veh_repair_price_month",#models.ArrayField(models.IntegerField(), size=2)
            # "vehicles_num",#models.IntegerField() # 4  - no !!!    but  11
            "vehicles_purchase_num",
            "vehicles_whtransfer_num",
            # vehicles and fuel_price and fuel_type are static
            "vehicle_name",#models.CharField(max_length=60, default='Ford Transit FT-190L')
            "vehicle_price",#models.FloatField() # 25000.0
            "fuel_price",#models.FloatField() # 28.73
            "fuel_type",#models.CharField(max_length=60)
            "vehicle_consumption",#models.FloatField() # 9.0
            
            # Purchase and WHTransfer for Purchase
            "delivery_added_time_koef",#models.FloatField() # 1.15 
            # "num_of_phs_on_1_vehicle",#models.IntegerField() # 44/4 == 11   - no !!! but 44/11",#4 num_of_phs_on_1_vehicle
            # "warehouse_num",#models.IntegerField(default=44)

            # for WHTransfer between phs
            "number_to_dispatch",#models.IntegerField(default=300)
            # for creation PurchaseClaim
            "normal_purch_days",#models.IntegerField(default=28)
            # for Purchase
            "threshold_days",#models.IntegerField(default=7) # за сколько дней до предположительного исчерпания продуктов надо делать заявку на закупку

            # for products
            "number_of_products_names",#models.IntegerField() # 100
            "product_markup_rate",#models.ArrayField(models.FloatField(), size=2) # 0.25, 0.3
            "product_cost_price",#models.ArrayField(models.FloatField(), size=2)

            #for whproducts
            "whp_self_rate",#models.ArrayField(models.FloatField(), size=2) # 0.7, 1.5
            "whp_quantity",#models.ArrayField(models.IntegerField(), size=2) # 100, 200

            # for sale                                      for 1 whp in day
            "day_quantity_range",#models.ArrayField(models.IntegerField(), size=2) # 2, 5
            
            # SalaryPayment in accounts.worker creation in _up   == 8 types really worx
            "salary_pharmacist",#models.FloatField(default=7000.0) # salary_pharmacist_num",# warehouse_num*3  #models.ArrayField()
            "pharmacist_per_wh",#models.IntegerField(default=3) # pro zapas 1 (2 odnovremenno)
            # "pharmacist_num",#models.IntegerField()

            "salary_HR",#models.FloatField(default=11000.0)
            "HR_num",#models.IntegerField(default=6) # мониторят оценки в ассесментс модели и могут - уволить \ нанять  pharmacist - но изменения все равно делает админ или нет? могут понизить зп?

            # 1 для проверки ответов системы, так как все операции производятся ерп - системой (1 про запас) - посменно
            "salary_accounting_manager",#models.FloatField(default=8000.0)
            "accounting_manager_num",#models.IntegerField(default=2)
            # accounting_managers_num_per_company",#models.IntegerField(default=1)

            # 1
            "salary_director",#models.FloatField(default=15000.0)

            "salary_cleaner",#models.FloatField(default=5000.0)
            "cleaner_per_wh",#models.IntegerField(default=2) # pro zapas 1
            # "cleaner_num",#models.IntegerField()

            "salary_loader",#models.FloatField(default=7000.0)
            "loader_per_vehicle",#models.IntegerField(default=2) # pro zapas 1
            # "loader_num",#models.IntegerField()

            "salary_driver",#models.FloatField(default=10000.0)
            "driver_per_vehicle",#models.IntegerField(default=2) # pro zapas 1
            # "driver_num",#models.IntegerField()

            "salary_sys_admin",#models.FloatField(default=10000.0)
            "sys_admin_num",#models.IntegerField(default=2)
            
            #initial_num_of_clients_that_make_assesments_and_buys
            "num_of_clients",#models.IntegerField(default=88) 

            # for convinience in opening accounts
            "that_user_password",#models.CharField(default="that_user_111", max_length=30)

            "percent_pre_buy_max_prob",
            "ph_sp_max_prob",##5,
            "dpt_sp_max_prob",##5,
            "v_r_max_prob",##5,
            "product_cost_price_max_prob",#5,
            "d_q_r_max_prob",#5,
            "prob_of_worker_fired_dir",#01, # помимо того что предлагают на увольнение хр по фармацептами ( собственная вероятность увольнения ) на этот  месяц
            "prob_of_worker_fired_hr",#05,
            "prob_of_worker_fired_am",#05,
            "prob_of_worker_fired_sa",#08,
            "prob_of_worker_fired_cl",#3,
            "prob_of_worker_fired_ld",#4,
            "prob_of_worker_fired_dr",#15,
            "prob_of_worker_fired_ph",#1,
            "assesment_range",#=[1,5],
            "prob_of_client_assessment",#1,
            "prob_max_assesm_client",#8,
            "assesm_to_delete_worker",#=2,
            "threshold_bad_assesses",#=4,
            "prob_delete_worker"#3,

        ]

        # VEHICALS_NUM = (
        #         ('', 'Select the vehicles_num to calc amount pharmacies on 1 vehicle'),
        #         ('1', '1'), #First one is the value of select option and second is the displayed value in option
        #         ('2', '2'),
        #         ('4', '4'),
        #         ('11', '11'), # this to choose !!!
        #         ('22', '22'),
        #         ('44', '44'),
        #         )
        # widgets = {
        #     'vehicles_num': forms.Select(choices=VEHICALS_NUM, attrs={'class': 'form-control'}),
        # }
        TVEHICALS_NUM = (
                ('', 'Select the vehicles_purchase_num to perform purchase transfering'),
                ('1', '1'), #First one is the value of select option and second is the displayed value in option
                ('2', '2'),
                ('4', '4'),
                ('11', '11'), # this to choose !!!
                ('22', '22'),
                ('44', '44'),
                )
        widgets = {
            'vehicles_purchase_num': forms.Select(choices=TVEHICALS_NUM, attrs={'class': 'form-control'}),
        }
        PVEHICALS_NUM = (
                ('', 'Select the vehicles_whtransfer_num to perform whtransfer transfering to calc amount pharmacies on 1 vehicle'),
                ('1', '1'), #First one is the value of select option and second is the displayed value in option
                ('2', '2'),
                ('4', '4'),
                ('11', '11'), # this to choose !!!
                ('22', '22'),
                ('44', '44'),
                )
        widgets = {
            'vehicles_whtransfer_num': forms.Select(choices=PVEHICALS_NUM, attrs={'class': 'form-control'}),
        }

simulation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.http import HttpResponseBadRequest, HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.core import serializers

import json
import datetime

from .models import Simulation, get_simulation
from .forms import SimulationForm

# Create your views here.

def simulation_page(request):
    context = {
        "simulations_exists": Simulation.objects.all().exists()
	}
    return render(request, 'simulation_page.html', context)

# надо будет додумать форму для симуляции а пока пользуемся автозаполнением
def simulation_create(request):
    form = SimulationForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.today = datetime.date.today()
        instance.save()
        return HttpResponseRedirect(reverse('simulation:simulation_page'))
    context = {
        "form": form,
    }
    return render(request, "simulation_form.html", context)

def simulation_model_inner_data(request):
    simulations_exists = False
    if Simulation.objects.all().exists():
        sim = get_simulation()
        data = [[field.name, getattr(sim, field.name)] for field in sim._meta.get_fields()]
        # data = serializers.serialize("python", data)
        # data = [[key, value] for key, value in data.__dict__.items]
        print(data)
        simulations_exists = True
    context = {
        "simulations_exists": simulations_exists,
        "data": data
    }
    return render(request, "simulation_data.html", context)

def simulation_auto_create(request):
    # integrety error simulation_simulation_pkey
    Simulation.objects.create(
				#1
		whp_quantity=[20, 70], # down # there - [5, 70] - [20, 70]
		#1
		#2
		assesment_range=[1, 5],
        prob_of_client_assessment=0.5, # up 0.4 - 0.5
        prob_max_assesm_client=0.3, # down  0.5 - 0.3
        assesm_to_delete_worker=3, # up 2 - 3
        threshold_bad_assesses=2, # down 4 - 2
        prob_delete_worker=0.5, # up 0.4 -  0.5
		#2
		#1,3
		percent_pre_buy_max_prob=0.2, # down 0.5 - 0.2
		percent_pre_buy=[0.2, 0.4], # down [0.4, 0.7] - [0.2, 0.4]
		d_q_r_max_prob=0.2, # down 0.6 - 0.2
		day_quantity_range=[0, 3], # down [1, 5] - [0, 3]
        whp_self_rate=[0.3, 0.8], # down [0.5, 1.1] - [0.3, 0.8]
		#1,3
		#3
		ph_sp_max_prob=0.99, # up 0.8 - 0.99
        dpt_sp_max_prob=0.99, # up 0.8 - 0.99
        v_r_max_prob=0.99, # up 0.8 - 0.99
		pharmacys_spendingds=[1500, 2000], # up [600, 900], [1500, 2000],
        department_spendingds=[15000, 20000], # up [6000, 9000], [15000, 20000],
        veh_repair_price_month=[15000, 20000], # up [6000, 9000], [15000, 20000],
		
        salary_pharmacist=21000.0,
        pharmacist_per_wh=3,
        salary_HR=33000.0,
        HR_num=6,
        salary_accounting_manager=24000.0,
        accounting_manager_num=2,
        salary_director=45000.0,
        salary_cleaner=15000.0,
        cleaner_per_wh=2,
        salary_loader=21000.0,
        loader_per_vehicle=2,
        salary_driver=30000.0,
        driver_per_vehicle=2,
        salary_sys_admin=30000.0,
        sys_admin_num=2,
		#3
		#---
        product_cost_price_max_prob=0.5,
        prob_of_worker_fired_dir=0.001,                                                                          
        prob_of_worker_fired_hr=0.005,
        prob_of_worker_fired_am=0.005,
        prob_of_worker_fired_sa=0.008,
        prob_of_worker_fired_cl=0.03,
        prob_of_worker_fired_ld=0.004,
        prob_of_worker_fired_dr=0.015,
        prob_of_worker_fired_ph=0.01,

        auto_populated=True,
        today=datetime.date.today(),
        today_time=datetime.datetime.today(),
        minimal_zp=4173,
        pharmacys_sizes=40.0,
        department_size=300.0,
        tax_property_size_limit=60.0,
        vehicles_purchase_num=11,
        vehicles_whtransfer_num=4,
        vehicle_name='Ford Transit FT-190L',
        vehicle_price=25000.0,
        fuel_price=28.73,
        fuel_type='A-95',
        vehicle_consumption=9.0,
        delivery_added_time_koef=1.15,
        number_to_dispatch=100,
        normal_purch_days=28,
        threshold_days=7,
        number_of_products_names=20,
        product_markup_rate=[0.25, 0.3],
        product_cost_price=[20.0, 500.0],
        num_of_clients=88,
        # for convinience in opening accounts
        that_user_password="that_user_111"
    )
    return HttpResponseRedirect(reverse('simulation:simulation_page'))

def simulate(request, action):
    # print('action: ', action)
    sim = get_simulation()
    if action == "disable" and sim.status == True:
        sim.status = False
        sim.save()
    elif action == "enable" and sim.status == False:
        sim.status = True
        sim.save()
    context = {
            "simulations_exists": True,
            "days_passed": sim.get_simulation_day(),
            "simulation_today_str": (sim.today).strftime("%d %B, %Y"), # 06/12/18  ->  12 June, 2018
            "simulation_status": sim.status
    }
    return render(request, "simulation_page.html", context=context)


# def refresh_simulation_info(request):
def current_simulation_info(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        from_url = data['from_url']
        sim = get_simulation()
        context = {
                "days_passed": sim.get_simulation_day(),
                "simulation_today_str": (sim.today).strftime("%d %B, %Y"), # 06/12/18  ->  12 June, 2018
                "simulation_status": sim.status
            }
        redirect(from_url)
        return JsonResponse(context)
    return HttpResponseBadRequest()
    

templates/accounting_main_page.html
{% extends "base.html" %}

{% block content %}
<hr>
<p><a href="{% url 'simulation:simulation_page' %}">Go back to Main Simulation Page</a></p>
<hr>
<h1>Accounting</h1>
<div class='container'>
{% if not simulations_exists %}
    <p><a href="{% url 'simulation:simulation_create' %}">Create First Simulation</a></p>
    <hr>
    <p><a href="{% url 'simulation:simulation_auto_create' %}">AutoCreate First Simulation</a></p>
{% else %}
    <p><a href="{% url 'general_accounting:accounting_balance' %}"> Get Accounting Balance</a></p>
    <hr>
    <p><a href="{% url 'general_accounting:trial_balance' %}">Get Trial Balance</a></p>
    <hr>
    <p><a href="{% url 'general_accounting:list_of_abs' %}"> Show all Accounting Balances</a></p>
    <hr>
    <p><a href="{% url 'general_accounting:list_of_tbs' %}">Show all Trial Balances</a></p>
{% endif %}
</div>
{% endblock content %}

templates/hfcs_list.html
{% extends "base.html" %}

{% block content %}
<h1>Hire Fire Checks</h1>
<hr>
<p><a href="{% url 'simulation:simulation_page' %}">Go back to Main Simulation Page</a></p>
<hr>
<div class='container'>
    {% if exists %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID HFC</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                {% for id in ids %}
                <div class="list-group">
                    <tr class="table-info">
                        <td>
                            <a href="{% url 'company_operations:certain_hfc' id %}" class='btn btn-primary btn-sm'>{{ id }}</a>
                        </td>
                    </tr>
                </div>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <hr>
    <h3>There is no Hire Fire Checks in system ( wait till creation, cause it happened every month \\ but there is an error ceratinly)</h3>
    {% endif %}
<div class='container'>
{% endblock content %}

templates/inventory_tracking.html
{% extends "base.html" %}

{% block content %}
<hr>
<p><a href="{% url 'simulation:simulation_page' %}">Go back to Main Simulation Page</a></p>
<hr>
<h1>Inventory Tracking</h1>
<hr>
{% if purchases %}
<p><a href="{% url 'company_operations:inventory_tracking_wht_delivery' %}">Get WareHouse Transfer tracking data</a></p>
<div class='container'>
    <h1>Purchased Inventory Tracking</h1>
    {% if suitable_objects_exists %}
        <h2>Vehicals reaching destinations info:</h2>
            {% for vr_info in veh_reaching_data %}
            <h4>{{vr_info}}</h4>
            {% endfor %}         
            <hr>
        <h2>Vehicles that already transfering products to destination:</h2>
            {% for id_t in transfering_vehicals %}
            <h4>Vehicle id: {{id_t}}</h4>
            {% endfor %}
        <hr>
        <h2>Vehicles that just reaching start destination:</h2>
            {% for id_not_t in not_transfering_vehicals %}
            <h4>Vehicle id: {{id_not_t}}</h4>
            {% endfor %}
        <hr>         
    {% else %}
    {% if objects_exists %}
    <h3>There is no started purchase transfers now in system</h3>
    {% else %}
    <h3>There is no purchase transfers now in system at all</h3>
    {% endif %}
    {% endif %}
</div>
{% else %}
<div class='container'>
<p><a href="{% url 'company_operations:inventory_tracking_purchase_delivery' %}">Get Purchase Transfer tracking data</a></p>
<div class='container'>
    <h1>Transfered Inventory Tracking</h1>
    {% if suitable_objects_exists %}
        <h2>Vehicals reaching destinations info:</h2>
            {% for vr_info in veh_reaching_data %}
            <h4>{{vr_info}}</h4>
            {% endfor %}         
            <hr>
        <h2>Vehicles that already transfering products to destination:</h2>
            {% for id_t in transfering_vehicals %}
            <h4>Vehicle id: {{id_t}}</h4>
            {% endfor %}
        <hr>
        <h2>Vehicles that just reaching start destination:</h2>
            {% for id_not_t in not_transfering_vehicals %}
            <h4>Vehicle id: {{id_not_t}}</h4>
            {% endfor %}
        <hr>         
    {% else %}
    {% if objects_exists %}
    <h3>There is no started warehouse transfers now in system</h3>
    {% else %}
    <h3>There is no warehouse transfers now in system at all</h3>
    {% endif %}
    {% endif %}
</div>
{% endif %}
{% endblock content %}

templates/list_of_abs.html
{% extends "base.html" %}

{% block content %}
<h1>Accounting Balances</h1>
<hr>
<p><a href="{% url 'general_accounting:accounting_main_page' %}">Go back to Main Accounting Page</a></p>
<hr>
<div class='container'>
    {% if exists %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID TB</th>
                    <th>Operative Day</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                {% for id, data_reported in data %}
                <div class="list-group">
                    <tr class="table-info">
                        <td>
                            <a href="{% url 'general_accounting:certain_ab' id %}" class='btn btn-primary btn-sm'>{{ id }}</a>
                        </td>
                        <td>
                            {{ data_reported|date:"d.m.Y" }}
                        </td>
                    </tr>
                </div>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <hr>
    <h3>There is no Trial Balances in system ( create TB or create simulation to create TB )</h3>
    {% endif %}
<div class='container'>
{% endblock content %}

templates/list_of_tbs.html
{% extends "base.html" %}

{% block content %}
<hr>
<p><a href="{% url 'simulation:simulation_page' %}">Go back to Main Simulation Page</a></p>
<hr>
<h1>Trial Balances</h1>
<hr>
<p><a href="{% url 'general_accounting:accounting_main_page' %}">Go back to Main Accounting Page</a></p>
<hr>
<div class='container'>
    {% if exists %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID TB</th>
                    <th>Operative Day</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                {% for id, data_reported in data %}
                <div class="list-group">
                    <tr class="table-info">
                        <td>
                            <a href="{% url 'general_accounting:certain_tb' id %}" class='btn btn-primary btn-sm'>{{ id }}</a>
                        </td>
                        <td>
                            {{ data_reported|date:"d.m.Y" }}
                        </td>
                    </tr>
                </div>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <hr>
    <h3>There is no Trial Balances in system ( create TB or create simulation to create TB )</h3>
    {% endif %}
<div class='container'>
{% endblock content %}

templates/shiet.html
<!-- <p>Правый клик вызывает меню документа (добавлена проверка event.defaultPrevented)</p>
<button id="elem">Правый клик вызывает меню кнопки</button>
<button id="df">Правый клик вызывает меню </button>

<script>
  elem.oncontextmenu = function(event) {
    event.preventDefault();
    alert("Контекстное меню кнопки");
  };

//   df.oncontextmenu = function(event) {
//     event.preventDefault(false);
//   };

  document.oncontextmenu = function(event) {
    if (event.defaultPrevented) return;

    event.preventDefault();
    alert("Контекстное меню документа");
  };
</script> -->
{% extends "base.html" %}

{% block content %}
<div class='container'>
  <h1>There is and getted from url info: {{ info }}</h1>
</div>
{% endblock content %}

templates/simulation_data.html
{% extends "base.html" %}

{% block content %}
<h1>Trial Balance</h1>
<hr>
<p><a href="{% url 'simulation:simulation_page' %}">Go back to Main Simulation Page</a></p>
<hr>
<div class='container'>
        {% if not simulations_exists %}
        <h1>There is no Simulations in the database</h1>
        <p><a href="{% url 'simulation:simulation_create' %}">Create First Simulation</a></p>
        <hr>
        <p><a href="{% url 'simulation:simulation_auto_create' %}">AutoCreate First Simulation</a></p>
        {% else %}
        <h1>All Simulation inner data:</h1>
        <hr>
        {% for key, value in data %}
            <h3><i>{{ key }}: {{ value }}</i></h3>
        {% endfor %}
        {% endif %}
</div>
{% endblock content %}

templates/simulation_page.html
{% extends "base.html" %}

{% block content %}
<h1>Simulation</h1>
<div class='container'>
{% if not simulations_exists %}
    <p><a href="{% url 'simulation:simulation_create' %}">Create First Simulation</a></p>
    <hr>
    <p><a href="{% url 'simulation:simulation_auto_create' %}">AutoCreate First Simulation</a></p>
{% else %}
    <p><a href="{% url 'simulation:simulation_data' %}" class="btn btn-primary" role="button">Simulation Inner Data</a></p>
    {% if not simulation_status %}
        <p><a href="{% url 'simulation:simulate' 'enable' %}" class="btn btn-primary" role="button">Start Simulation</a></p>
    {% else %}
        <h3><i id='days_passed'>days_passed: {{days_passed}}</i></h3>
        <h3><i id='simulation_today_str'>simulation_today_str: {{simulation_today_str}}</i></h3>
        <h3><i id='simulation_status'>simulation_status: {{simulation_status}}</i></h3>
        <hr>
        <p><a data-to-url="{% url 'simulation:current_simulation_info' %}" data-from-url="{{ request.get_full_path }}" onclick="refresh_simulation(this)" class="btn btn-info" role="button">Refresh Simulation</a></p>
        <hr>
        <p><a href="{% url 'simulation:simulate' 'disable' %}" class="btn btn-danger" role="button">Stop Simulation</a></p>
    {% endif %}
    <hr>
    <p><a href="{% url 'company_operations:list_of_hfcs' %}">Go watch HFC Lists</a></p>
    <hr>
    <p><a href="{% url 'general_accounting:accounting_main_page' %}">Go watch General Accounting</a></p>
    <hr>
    <p><a href="{% url 'company_operations:inventory_tracking_wht_delivery' %}">Get WareHouse Transfer tracking data</a></p>
    <hr>
    <p><a href="{% url 'company_operations:inventory_tracking_purchase_delivery' %}">Get Purchase Transfer tracking data</a></p>
{% endif %}
</div>
{% endblock content %}